# Generated by Django 5.1.6 on 2025-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medication_created_at_medication_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medication',
            name='reorder_level',
            field=models.IntegerField(default=10),
        ),
    ]
